name: Build and deploy aleo-snap

env:
  NODE_VERSION: "14.x"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-aleo-snap:
    name: "Deploy aleo-snap"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install latest stable Rust version
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Buid aleo-wasm
        run:  wasm-pack build --target web
        working-directory: aleo/wasm  
      
      - name: Install aleo-wasm-bundler
        uses: bahmutov/npm-install@v1
        with:
          working-directory: aleo-wasm-bundler
          
      - name: Buid aleo-wasm-bundler
        run: npx patch-package && yarn build
        working-directory: aleo-wasm-bundler
        
      - name: Install aleo-snap
        uses: bahmutov/npm-install@v1
        with:
          working-directory: aleo-snap

      - name: Build aleo-snap
        run: yarn build && yarn build:website
        working-directory: aleo-snap

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.0
        with:
          publish-dir: "./aleo-snap/dist"
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_ALEO_SNAP }}